http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  ipapi:
    host: apps.raleighnc.gov
    paths: '/ip'         
  cwapi:
    host: apps.raleighnc.gov
    paths: '/getServiceRequest/*'     
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  cityworks:
    url: 'http://rhsoatstapp1.ci.raleigh.nc.us:8182/RaleighAPI/cityworks/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: one
    apiEndpoints:
      - ipapi
    policies:
    #  - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  - name: two
    apiEndpoints:
      - cwapi
    policies:
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: cityworks 
              changeOrigin: true
         

