http:
  port: 8080
admin:
  port: 9876
  hostname: ptletctstapplv1
apiEndpoints:
  ipapi:
    host: ptletctstapplv1
    paths: '/ip'         
  cwapi:
    host: ptletctstapplv1
    paths: 
      - '/*'
#      - '/getServiceRequest/*'
#      - '/createServiceRequest'
  cwapp:
    host: ptletctstapplv1
    paths:
      - '/cityworkstest/*'      
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  cityworksapi:
    url: 'http://rhsoaprdapp1.ci.raleigh.nc.us:8183/RaleighAPI/cityworks'
  cityworks:
    url: 'http://cworktstappwv1'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: one
    apiEndpoints:
      - ipapi
    policies:
#      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  - name: two
    apiEndpoints:
      - cwapi
    policies:
      - cors:
          - action:
              name: cors
              origin: https://maps.raleighnc.gov
              credentials: true
#      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: cityworksapi 
              changeOrigin: true
  - name: three
      apiEndpoints:
        - cwapp
      policies:
        - cors:
#        - key-auth:
        - proxy:
            - action:
                serviceEndpoint: cityworks 
                changeOrigin: true

